# Generated by Django 5.2.17 on 2026-09-23 15:51

import apps.motos.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='patente')),
                ('marca', models.CharField(max_length=80, verbose_name='marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='modelo')),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True, validators=[apps.motos.models.validar_anio], verbose_name='año')),
                ('cilindrada_cc', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cilindrada')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='color')),
                ('kilometraje_actual', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='último kilometraje registrado')),
                ('numero_chasis', models.CharField(blank=True, max_length=100, verbose_name='número de chasis')),
                ('numero_motor', models.CharField(blank=True, max_length=100, verbose_name='número de motor')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizada el')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motos', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'moto',
                'verbose_name_plural': 'motos',
                'ordering': ('marca', 'modelo', 'pk'),
            },
        ),
    ]
