# Generated by Django 5.2.17 on 2026-09-24 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('mantenimientos', '0004_tipomantenimiento_aviso_dias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTACTADO', 'Contactado'), ('POSPUESTO', 'Pospuesto'), ('TURNO_ACORDADO', 'Turno acordado'), ('NO_INTERESADO', 'No interesado')], default='PENDIENTE', max_length=16, verbose_name='estado')),
                ('pospuesto_hasta', models.DateField(blank=True, null=True, verbose_name='pospuesto hasta')),
                ('turno_para', models.DateTimeField(blank=True, null=True, verbose_name='turno para')),
                ('ultimo_contacto_en', models.DateTimeField(blank=True, null=True, verbose_name='último contacto el')),
                ('observaciones', models.TextField(blank=True, verbose_name='nota operativa')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_mantenimiento', to='clientes.cliente', verbose_name='cliente contactado')),
                ('mantenimiento_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='mantenimientos.mantenimientorealizado', verbose_name='mantenimiento base')),
                ('ultimo_contacto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='último contacto por')),
            ],
            options={
                'verbose_name': 'seguimiento de mantenimiento',
                'verbose_name_plural': 'seguimientos de mantenimiento',
                'ordering': ('-actualizado_en', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='EventoSeguimientoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CONTACTADO', 'Contactado'), ('POSPUESTO', 'Pospuesto'), ('TURNO_ACORDADO', 'Turno acordado'), ('NO_INTERESADO', 'No interesado'), ('REABIERTO', 'Reabierto'), ('NOTA', 'Nota')], max_length=16, verbose_name='tipo de evento')),
                ('nota', models.TextField(blank=True, verbose_name='nota')),
                ('pospuesto_hasta', models.DateField(blank=True, null=True, verbose_name='pospuesto hasta')),
                ('turno_para', models.DateTimeField(blank=True, null=True, verbose_name='turno para')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='notificaciones.seguimientomantenimiento', verbose_name='seguimiento')),
            ],
            options={
                'verbose_name': 'evento de seguimiento',
                'verbose_name_plural': 'eventos de seguimiento',
                'ordering': ('creado_en', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='seguimientomantenimiento',
            constraint=models.UniqueConstraint(fields=('mantenimiento_base', 'cliente'), name='seguimiento_ciclo_cliente_unico'),
        ),
        migrations.AddConstraint(
            model_name='seguimientomantenimiento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'POSPUESTO'), _negated=True), ('pospuesto_hasta__isnull', False), _connector='OR'), name='seguimiento_pospuesto_con_fecha'),
        ),
        migrations.AddConstraint(
            model_name='seguimientomantenimiento',
            constraint=models.CheckConstraint(condition=models.Q(('estado', 'POSPUESTO'), ('pospuesto_hasta__isnull', True), _connector='OR'), name='seguimiento_fecha_solo_pospuesto'),
        ),
        migrations.AddConstraint(
            model_name='seguimientomantenimiento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'TURNO_ACORDADO'), _negated=True), ('turno_para__isnull', False), _connector='OR'), name='seguimiento_turno_con_fecha'),
        ),
        migrations.AddConstraint(
            model_name='seguimientomantenimiento',
            constraint=models.CheckConstraint(condition=models.Q(('estado', 'TURNO_ACORDADO'), ('turno_para__isnull', True), _connector='OR'), name='seguimiento_fecha_solo_turno'),
        ),
        migrations.AddConstraint(
            model_name='eventoseguimientomantenimiento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo_evento', 'POSPUESTO'), _negated=True), ('pospuesto_hasta__isnull', False), _connector='OR'), name='evento_pospuesto_con_fecha'),
        ),
        migrations.AddConstraint(
            model_name='eventoseguimientomantenimiento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo_evento', 'TURNO_ACORDADO'), _negated=True), ('turno_para__isnull', False), _connector='OR'), name='evento_turno_con_fecha'),
        ),
    ]
