# Generated by Django 5.2.17 on 2026-09-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name='apellido')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('apellido', 'nombre', 'pk'),
            },
        ),
    ]
