# Generated by Django 5.2.17 on 2026-09-23 17:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0001_initial"),
        ("motos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="fecha"),
                ),
                (
                    "kilometraje",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="kilometraje",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABIERTO", "Abierto"),
                            ("FINALIZADO", "Finalizado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="FINALIZADO",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                ("trabajos_adicionales", models.TextField(blank=True, verbose_name="otros trabajos")),
                ("observaciones", models.TextField(blank=True, verbose_name="observaciones")),
                (
                    "precio_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="precio total",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True, verbose_name="creado el")),
                ("actualizado_en", models.DateTimeField(auto_now=True, verbose_name="actualizado el")),
                (
                    "cliente",
                    models.ForeignKey(
                        help_text="Propietario de la moto al registrar el servicio.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servicios",
                        to="clientes.cliente",
                        verbose_name="cliente atendido",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servicios_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "moto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servicios",
                        to="motos.moto",
                        verbose_name="moto",
                    ),
                ),
            ],
            options={
                "verbose_name": "servicio",
                "verbose_name_plural": "servicios",
                "ordering": ("-fecha", "-pk"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("precio_total__isnull", True),
                            ("precio_total__gte", 0),
                            _connector="OR",
                        ),
                        name="servicio_precio_total_no_negativo",
                    )
                ],
            },
        ),
    ]
