# Generated by Django 5.2.17 on 2026-09-23 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimientos', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientorealizado',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_realizados', to='servicios.servicio', verbose_name='servicio'),
        ),
        migrations.AddField(
            model_name='mantenimientorealizado',
            name='tipo_mantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realizaciones', to='mantenimientos.tipomantenimiento', verbose_name='tipo de mantenimiento'),
        ),
        migrations.AddConstraint(
            model_name='mantenimientorealizado',
            constraint=models.UniqueConstraint(fields=('servicio', 'tipo_mantenimiento'), name='servicio_tipo_mantenimiento_unico'),
        ),
    ]
