# Generated by Django 5.2.17 on 2026-09-24 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0003_cargar_catalogo_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomantenimiento',
            name='aviso_dias',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aviso anticipado en días'),
        ),
        migrations.AddField(
            model_name='tipomantenimiento',
            name='aviso_km',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aviso anticipado en kilómetros'),
        ),
        migrations.AddField(
            model_name='tipomantenimiento',
            name='genera_recordatorio',
            field=models.BooleanField(default=False, verbose_name='genera recordatorio'),
        ),
        migrations.AddField(
            model_name='tipomantenimiento',
            name='intervalo_km',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='intervalo en kilómetros'),
        ),
        migrations.AddField(
            model_name='tipomantenimiento',
            name='intervalo_meses',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='intervalo en meses'),
        ),
        migrations.AddConstraint(
            model_name='tipomantenimiento',
            constraint=models.CheckConstraint(condition=models.Q(('intervalo_meses__isnull', True), ('intervalo_meses__gte', 1), _connector='OR'), name='tipo_intervalo_meses_positivo'),
        ),
        migrations.AddConstraint(
            model_name='tipomantenimiento',
            constraint=models.CheckConstraint(condition=models.Q(('intervalo_km__isnull', True), ('intervalo_km__gte', 1), _connector='OR'), name='tipo_intervalo_km_positivo'),
        ),
        migrations.AddConstraint(
            model_name='tipomantenimiento',
            constraint=models.CheckConstraint(condition=models.Q(('aviso_dias__gte', 0)), name='tipo_aviso_dias_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='tipomantenimiento',
            constraint=models.CheckConstraint(condition=models.Q(('aviso_km__gte', 0)), name='tipo_aviso_km_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='tipomantenimiento',
            constraint=models.CheckConstraint(condition=models.Q(('genera_recordatorio', False), ('intervalo_meses__isnull', False), ('intervalo_km__isnull', False), _connector='OR'), name='tipo_recordatorio_con_intervalo'),
        ),
    ]
